name: Build and release Weather app
on:
  push:
    branches:
      - 'main'

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO_URL }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.x

      - name: Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build Android APK
        run: |
          eas build --profile preview --platform android --non-interactive --clear-cache --local
          mv ./*.apk Weather-v1.apk 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        with:
          tag_name: v1
          release_name: Weather v1
          body: |
            Changelog
            - Initial build
          draft: false
          prerelease: false

      - name: Upload asset to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Weather-v1.apk
          asset_name: Weather-v1.apk
          asset_content_type: application/vnd.android.package-archive
          